package views;


import controllers.NewController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import models.Course;
import models.CourseList;



public class NewPanel extends javax.swing.JPanel {

    private DefaultTableModel tableModelAll;
    private DefaultTableModel tableModelPos;
    private NewController controller;
    
  
    
    
    public NewPanel() {
        
        initComponents();
        tableModelAll = (DefaultTableModel) jTableAll.getModel();
        tableModelPos = (DefaultTableModel) jTablePositive.getModel();
        
    }
    
    public void setAllCourses(CourseList c){
        if (c!= null){
            List<Course> courses = c.getCourses();
            tableModelAll.setRowCount(0);
            if (courses != null){
                courses.forEach(course -> {
                    tableModelAll.addRow(new Object[] {course.getTitle(), course.getEcts()});
                });
            }
        }
        else{
            while(tableModelAll.getRowCount() > 0){
                tableModelAll.removeRow(0);
            }
        }
        
    }
    
    public void setPosCourses(CourseList c){
        if (c!= null){
            List<Course> courses = c.getCourses();
            tableModelPos.setRowCount(0);
            if (courses != null){
                courses.forEach(course -> {
                    tableModelPos.addRow(new Object[] {course.getTitle(), course.getEcts()});
                });
            }
        }
        else{
            while(tableModelPos.getRowCount() > 0){
                tableModelPos.removeRow(0);
            }
        }
    }
    
    public void setController(NewController controller){
        this.controller = controller;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAll = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePositive = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jTextFieldMinECTS = new javax.swing.JTextField();
        jButtonCompute = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCourses = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jTableAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Predmet", "ECTS"
            }
        ));
        jScrollPane2.setViewportView(jTableAll);

        jTablePositive.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Predmet", "ECTS"
            }
        ));
        jScrollPane3.setViewportView(jTablePositive);

        jLabel1.setText("Vsi predmeti");

        jLabel2.setText("Pozitivni predmeti");

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. letnik", "2. letnik" }));
        jComboBoxYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxYearMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBoxYearMousePressed(evt);
            }
        });
        jComboBoxYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBoxYearKeyTyped(evt);
            }
        });

        jTextFieldMinECTS.setText("jTextField1");
        jTextFieldMinECTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMinECTSActionPerformed(evt);
            }
        });

        jButtonCompute.setText("Izračunaj");

        jLabel3.setText("Minimalni ECTS:");

        jTextFieldCourses.setEditable(false);
        jTextFieldCourses.setText("jTextField1");

        jLabel4.setText("Še potrebni predmeti:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldMinECTS, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonCompute, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMinECTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCompute)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMinECTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMinECTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMinECTSActionPerformed

    private void jComboBoxYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxYearKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxYearKeyTyped

    private void jComboBoxYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxYearMouseClicked
        
    }//GEN-LAST:event_jComboBoxYearMouseClicked

    private void jComboBoxYearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxYearMousePressed
        controller.yearControl(jComboBoxYear.getModel().getSelectedItem());
    }//GEN-LAST:event_jComboBoxYearMousePressed

 
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCompute;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableAll;
    private javax.swing.JTable jTablePositive;
    private javax.swing.JTextField jTextFieldCourses;
    private javax.swing.JTextField jTextFieldMinECTS;
    // End of variables declaration//GEN-END:variables
}
